server:
  port: ${PORT:0}

spring:
  
  application:
    name: ms-product
    
  config:
    import:
    - vault://
    
  cloud:

       config:
        enabled: true
       username: ${CONFIG_SERVER_USERNAME:admin}
       password: ${CONFIG_SERVER_PASSWORD:admin}
      
    vault:
      enabled: true
      uri: ${VAULT:http://localhost:8200}
      authentication: token
      token: ${VAULT_TOKEN:00000000-0000-0000-0000-000000000000}

  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
        '[event.merge.entity_copy_observer]': allow
    show-sql: true
    
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8086
        username: ${SBA_SERVER_USERNAME:admin}
        password: ${SBA_SERVER_PASSWORD:admin}


springdoc:

  title: "Product Api"
  description: "Api for product"
  version: "v1.0.0"
  contact-name: "Jean Ramal"
  contact-email: "jean.ramal@codearti.com"
  contact-url: "https://www.codearti.com"
  
  api-docs:
    path: /api-docs
#  packages-to-scan:
#  - com.codearti.application.rest
#  paths-to-match:
#  - /v1
  swagger-ui:
    path: /swagger-ui.html
#    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    enabled: true
#    service-url:
#      defaultZone: http://admin:admin@ms-discovery-server:8761/eureka
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
