server:
  port: ${PORT:0}

spring:
    
  datasource:
    driver-class-name: org.postgresql.Driver
  
#  h2:
#    console:
#      enabled: false
#      path: /h2-console
  
 
   
  
  boot:
    admin:
      client:
        enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    enabled: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
